plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.9'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'raisetech'
version = '0.0.1-SNAPSHOT'
description = 'studentManagementSystem'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}

	configurations {
		complileOnly{
			extendsFrom annotationProcessor
		}
	}
}
 
repositories {
	mavenCentral()
}

dependencies {
	//Spring boot
	implementation 'org.springframework.boot:spring-boot-starter-web'
	//Thymeleaf
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	//Apache commons lang 便利機能　ユーティリティ
	implementation 'org.apache.commons:commons-lang3:3.18.0'
	//Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	//MySQLドライバ
	runtimeOnly 'com.mysql:mysql-connector-j'

	//MyBatis
	implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:4.0.1'

	//providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
